// <auto-generated />
using FinalProject1.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProject1.Migrations
{
    [DbContext(typeof(MyContect))]
    [Migration("20240905182037_FirstCreate")]
    partial class FirstCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProject1.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Devices, gadgets, and accessories",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Fiction, non-fiction, and more",
                            Name = "Books"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Appliances for home use",
                            Name = "Home Appliances"
                        });
                });

            modelBuilder.Entity("FinalProject1.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Latest smartphone with advanced features",
                            ImagePath = "/images/smartphone.jpg",
                            Price = 699.99m,
                            Quantity = 50,
                            Title = "Smartphone X1"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "High-definition 4K television",
                            ImagePath = "/images/tv.jpg",
                            Price = 999.99m,
                            Quantity = 30,
                            Title = "4K Ultra HD TV"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "A thrilling fiction novel",
                            ImagePath = "/images/book.jpg",
                            Price = 19.99m,
                            Quantity = 100,
                            Title = "The Great Adventure Book"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Description = "High-speed blender with multiple settings",
                            ImagePath = "/images/blender.jpg",
                            Price = 59.99m,
                            Quantity = 20,
                            Title = "Blender Pro"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Headphones with active noise cancellation",
                            ImagePath = "/images/headphones.jpg",
                            Price = 199.99m,
                            Quantity = 80,
                            Title = "Noise-Cancelling Headphones"
                        });
                });

            modelBuilder.Entity("FinalProject1.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Ahmed@Gmail.com",
                            FirstName = "Ahmed",
                            LastName = "Ali",
                            Password = "Password123"
                        },
                        new
                        {
                            Id = 2,
                            Email = "B@Gmail.com",
                            FirstName = "Samy",
                            LastName = "Zain",
                            Password = "Password123"
                        },
                        new
                        {
                            Id = 3,
                            Email = "C@Gmail.com",
                            FirstName = "Ali",
                            LastName = "Marwan",
                            Password = "Password123"
                        },
                        new
                        {
                            Id = 4,
                            Email = "D@Gmail.com",
                            FirstName = "Samer",
                            LastName = "Mohamed",
                            Password = "Password123"
                        },
                        new
                        {
                            Id = 5,
                            Email = "E@Gmail.com",
                            FirstName = "Mayar",
                            LastName = "Shrif",
                            Password = "Password123"
                        },
                        new
                        {
                            Id = 6,
                            Email = "F@Gmail.com",
                            FirstName = "osama",
                            LastName = "Adly",
                            Password = "Password123"
                        },
                        new
                        {
                            Id = 7,
                            Email = "G@Gmail.com",
                            FirstName = "Sara",
                            LastName = "Salem",
                            Password = "Password123"
                        },
                        new
                        {
                            Id = 8,
                            Email = "H@Gmail.com",
                            FirstName = "zain",
                            LastName = "Ali",
                            Password = "Password123"
                        },
                        new
                        {
                            Id = 9,
                            Email = "I@Gmail.com",
                            FirstName = "Mahmoud",
                            LastName = "Salah",
                            Password = "Password123"
                        },
                        new
                        {
                            Id = 10,
                            Email = "J@Gmail.com",
                            FirstName = "yahia",
                            LastName = "Azmey",
                            Password = "Password123"
                        },
                        new
                        {
                            Id = 11,
                            Email = "K@Gmail.com",
                            FirstName = "tarek",
                            LastName = "Ahmed",
                            Password = "Password123"
                        },
                        new
                        {
                            Id = 12,
                            Email = "L@Gmail.com",
                            FirstName = "mansour",
                            LastName = "Ahmed",
                            Password = "Password123"
                        });
                });

            modelBuilder.Entity("FinalProject1.Models.Product", b =>
                {
                    b.HasOne("FinalProject1.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FinalProject1.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
